spring.application.name=shopflow-api
spring.datasource.url=jdbc:postgresql://localhost:5432/shopflow
spring.datasource.username=shopflow
spring.datasource.password=shopflow

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
