CREATE TABLE categories (
                            id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE product_categories (
                                    product_id  BIGINT NOT NULL REFERENCES products(id)   ON DELETE CASCADE,
                                    category_id BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
                                    PRIMARY KEY (product_id, category_id)
);