CREATE TABLE orders (
                        id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id    BIGINT NOT NULL REFERENCES users(id),
                        total      NUMERIC(12, 2) NOT NULL,
                        status     VARCHAR(50) NOT NULL,
                        created_at TIMESTAMP NOT NULL
);

CREATE TABLE order_items (
                             id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             order_id   BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
                             product_id BIGINT NOT NULL REFERENCES products(id),
                             quantity   INTEGER NOT NULL,
                             price      NUMERIC(12, 2) NOT NULL
);